### ISSUE TITLE
Legato isn't published to hex

### ISSUE THREAD

**Issue by elkelk** [tpitale/legato-ex#3]
It would be nice if Legato was listed as a hex package:

```
** (Mix) No package with name legato (from: mix.exs) in registry
```

**Comment by tpitale** [comment]
I had a reason, but I don't remember what it is now. Maybe it just wasn't ready yet.

Will look and try to publish in the morning.

**Comment by tpitale** [comment]
Sorry for the delay:

https://hex.pm/packages/legato/0.2.0
https://hexdocs.pm/legato/0.2.0
